name: check-crlf

on: 
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on master branch
      - master
      - check-crlf

jobs:
  example-workflow:
    name: Check CRLF action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: check-crlf
        uses: erclu/check-crlf@v1
